# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Strokes Expected Putts
# Calculation after base ones: y = 0.3916*Math.log(x) + 0.6486

StrokesExpectedPutt.destroy_all
StrokesExpectedPutt.create(distance: 1, strokes_expected: 1.00)
StrokesExpectedPutt.create(distance: 2, strokes_expected: 1.00)
distances = (3..75).to_a
distances.map do |dist|
  StrokesExpectedPutt.create(
    distance: dist,
    strokes_expected: ((0.3916*Math.log(dist)) + 0.6486).round(2)
  )
end

# Strokes Expected Shots
# Calculate each section in between....probably just average
StrokesExpectedShot.destroy_all

#Tee
StrokesExpectedShot.create(distance: 100, strokes_expected: 2.92, lie: 'T')
StrokesExpectedShot.create(distance: 105, strokes_expected: 2.94, lie: 'T')
StrokesExpectedShot.create(distance: 110, strokes_expected: 2.96, lie: 'T')
StrokesExpectedShot.create(distance: 115, strokes_expected: 2.98, lie: 'T')
StrokesExpectedShot.create(distance: 120, strokes_expected: 2.99, lie: 'T')
StrokesExpectedShot.create(distance: 125, strokes_expected: 2.99, lie: 'T')
StrokesExpectedShot.create(distance: 130, strokes_expected: 2.98, lie: 'T')
StrokesExpectedShot.create(distance: 135, strokes_expected: 2.98, lie: 'T')
StrokesExpectedShot.create(distance: 140, strokes_expected: 2.97, lie: 'T')
StrokesExpectedShot.create(distance: 145, strokes_expected: 2.98, lie: 'T')
StrokesExpectedShot.create(distance: 150, strokes_expected: 2.98, lie: 'T')
StrokesExpectedShot.create(distance: 155, strokes_expected: 2.99, lie: 'T')
StrokesExpectedShot.create(distance: 160, strokes_expected: 2.99, lie: 'T')
StrokesExpectedShot.create(distance: 165, strokes_expected: 3.01, lie: 'T')
StrokesExpectedShot.create(distance: 170, strokes_expected: 3.02, lie: 'T')
StrokesExpectedShot.create(distance: 175, strokes_expected: 3.04, lie: 'T')
StrokesExpectedShot.create(distance: 180, strokes_expected: 3.05, lie: 'T')
StrokesExpectedShot.create(distance: 185, strokes_expected: 3.07, lie: 'T')
StrokesExpectedShot.create(distance: 190, strokes_expected: 3.09, lie: 'T')
StrokesExpectedShot.create(distance: 195, strokes_expected: 3.11, lie: 'T')

StrokesExpectedShot.create(distance: 200, strokes_expected: 3.12, lie: 'T')
StrokesExpectedShot.create(distance: 205, strokes_expected: 3.14, lie: 'T')
StrokesExpectedShot.create(distance: 210, strokes_expected: 3.15, lie: 'T')
StrokesExpectedShot.create(distance: 215, strokes_expected: 3.16, lie: 'T')
StrokesExpectedShot.create(distance: 220, strokes_expected: 3.17, lie: 'T')
StrokesExpectedShot.create(distance: 225, strokes_expected: 3.19, lie: 'T')
StrokesExpectedShot.create(distance: 230, strokes_expected: 3.21, lie: 'T')
StrokesExpectedShot.create(distance: 235, strokes_expected: 3.23, lie: 'T')
StrokesExpectedShot.create(distance: 240, strokes_expected: 3.25, lie: 'T')
StrokesExpectedShot.create(distance: 245, strokes_expected: 3.30, lie: 'T')
StrokesExpectedShot.create(distance: 250, strokes_expected: 3.35, lie: 'T')
StrokesExpectedShot.create(distance: 255, strokes_expected: 3.40, lie: 'T')
StrokesExpectedShot.create(distance: 260, strokes_expected: 3.45, lie: 'T')
StrokesExpectedShot.create(distance: 265, strokes_expected: 3.50, lie: 'T')
StrokesExpectedShot.create(distance: 270, strokes_expected: 3.55, lie: 'T')
StrokesExpectedShot.create(distance: 275, strokes_expected: 3.60, lie: 'T')
StrokesExpectedShot.create(distance: 280, strokes_expected: 3.65, lie: 'T')
StrokesExpectedShot.create(distance: 285, strokes_expected: 3.67, lie: 'T')
StrokesExpectedShot.create(distance: 290, strokes_expected: 3.68, lie: 'T')
StrokesExpectedShot.create(distance: 295, strokes_expected: 3.70, lie: 'T')

StrokesExpectedShot.create(distance: 300, strokes_expected: 3.71, lie: 'T')
StrokesExpectedShot.create(distance: 305, strokes_expected: 3.73, lie: 'T')
StrokesExpectedShot.create(distance: 310, strokes_expected: 3.75, lie: 'T')
StrokesExpectedShot.create(distance: 315, strokes_expected: 3.73, lie: 'T')
StrokesExpectedShot.create(distance: 320, strokes_expected: 3.79, lie: 'T')
StrokesExpectedShot.create(distance: 325, strokes_expected: 3.81, lie: 'T')
StrokesExpectedShot.create(distance: 330, strokes_expected: 3.83, lie: 'T')
StrokesExpectedShot.create(distance: 335, strokes_expected: 3.85, lie: 'T')
StrokesExpectedShot.create(distance: 340, strokes_expected: 3.86, lie: 'T')
StrokesExpectedShot.create(distance: 345, strokes_expected: 3.88, lie: 'T')
StrokesExpectedShot.create(distance: 350, strokes_expected: 3.89, lie: 'T')
StrokesExpectedShot.create(distance: 355, strokes_expected: 3.91, lie: 'T')
StrokesExpectedShot.create(distance: 360, strokes_expected: 3.92, lie: 'T')
StrokesExpectedShot.create(distance: 365, strokes_expected: 3.93, lie: 'T')
StrokesExpectedShot.create(distance: 370, strokes_expected: 3.94, lie: 'T')
StrokesExpectedShot.create(distance: 375, strokes_expected: 3.95, lie: 'T')
StrokesExpectedShot.create(distance: 380, strokes_expected: 3.96, lie: 'T')
StrokesExpectedShot.create(distance: 385, strokes_expected: 3.97, lie: 'T')
StrokesExpectedShot.create(distance: 390, strokes_expected: 3.98, lie: 'T')
StrokesExpectedShot.create(distance: 395, strokes_expected: 3.99, lie: 'T')

StrokesExpectedShot.create(distance: 400, strokes_expected: 3.99, lie: 'T')
StrokesExpectedShot.create(distance: 405, strokes_expected: 4.00, lie: 'T')
StrokesExpectedShot.create(distance: 410, strokes_expected: 4.01, lie: 'T')
StrokesExpectedShot.create(distance: 415, strokes_expected: 4.02, lie: 'T')
StrokesExpectedShot.create(distance: 420, strokes_expected: 4.02, lie: 'T')
StrokesExpectedShot.create(distance: 425, strokes_expected: 4.03, lie: 'T')
StrokesExpectedShot.create(distance: 430, strokes_expected: 4.05, lie: 'T')
StrokesExpectedShot.create(distance: 435, strokes_expected: 4.07, lie: 'T')
StrokesExpectedShot.create(distance: 440, strokes_expected: 4.08, lie: 'T')
StrokesExpectedShot.create(distance: 445, strokes_expected: 4.11, lie: 'T')
StrokesExpectedShot.create(distance: 450, strokes_expected: 4.13, lie: 'T')
StrokesExpectedShot.create(distance: 455, strokes_expected: 4.15, lie: 'T')
StrokesExpectedShot.create(distance: 460, strokes_expected: 4.17, lie: 'T')
StrokesExpectedShot.create(distance: 465, strokes_expected: 4.20, lie: 'T')
StrokesExpectedShot.create(distance: 470, strokes_expected: 4.23, lie: 'T')
StrokesExpectedShot.create(distance: 475, strokes_expected: 4.25, lie: 'T')
StrokesExpectedShot.create(distance: 480, strokes_expected: 4.28, lie: 'T')
StrokesExpectedShot.create(distance: 485, strokes_expected: 4.32, lie: 'T')
StrokesExpectedShot.create(distance: 490, strokes_expected: 4.35, lie: 'T')
StrokesExpectedShot.create(distance: 495, strokes_expected: 4.38, lie: 'T')

StrokesExpectedShot.create(distance: 500, strokes_expected: 4.41, lie: 'T')
StrokesExpectedShot.create(distance: 505, strokes_expected: 4.45, lie: 'T')
StrokesExpectedShot.create(distance: 510, strokes_expected: 4.48, lie: 'T')
StrokesExpectedShot.create(distance: 515, strokes_expected: 4.51, lie: 'T')
StrokesExpectedShot.create(distance: 520, strokes_expected: 4.54, lie: 'T')
StrokesExpectedShot.create(distance: 525, strokes_expected: 4.57, lie: 'T')
StrokesExpectedShot.create(distance: 530, strokes_expected: 4.60, lie: 'T')
StrokesExpectedShot.create(distance: 535, strokes_expected: 4.63, lie: 'T')
StrokesExpectedShot.create(distance: 540, strokes_expected: 4.65, lie: 'T')
StrokesExpectedShot.create(distance: 545, strokes_expected: 4.68, lie: 'T')
StrokesExpectedShot.create(distance: 550, strokes_expected: 4.70, lie: 'T')
StrokesExpectedShot.create(distance: 555, strokes_expected: 4.72, lie: 'T')
StrokesExpectedShot.create(distance: 560, strokes_expected: 4.74, lie: 'T')
StrokesExpectedShot.create(distance: 565, strokes_expected: 4.76, lie: 'T')
StrokesExpectedShot.create(distance: 570, strokes_expected: 4.77, lie: 'T')
StrokesExpectedShot.create(distance: 575, strokes_expected: 4.78, lie: 'T')
StrokesExpectedShot.create(distance: 580, strokes_expected: 4.79, lie: 'T')
StrokesExpectedShot.create(distance: 585, strokes_expected: 4.80, lie: 'T')
StrokesExpectedShot.create(distance: 590, strokes_expected: 4.81, lie: 'T')
StrokesExpectedShot.create(distance: 595, strokes_expected: 4.82, lie: 'T')
StrokesExpectedShot.create(distance: 600, strokes_expected: 4.82, lie: 'T')

#Fairway
StrokesExpectedShot.create(distance: 10, strokes_expected: 2.30, lie: 'F')
StrokesExpectedShot.create(distance: 15, strokes_expected: 2.35, lie: 'F')
StrokesExpectedShot.create(distance: 20, strokes_expected: 2.40, lie: 'F')
StrokesExpectedShot.create(distance: 25, strokes_expected: 2.45, lie: 'F')
StrokesExpectedShot.create(distance: 30, strokes_expected: 2.50, lie: 'F')
StrokesExpectedShot.create(distance: 35, strokes_expected: 2.55, lie: 'F')
StrokesExpectedShot.create(distance: 40, strokes_expected: 2.60, lie: 'F')
StrokesExpectedShot.create(distance: 45, strokes_expected: 2.63, lie: 'F')
StrokesExpectedShot.create(distance: 50, strokes_expected: 2.65, lie: 'F')
StrokesExpectedShot.create(distance: 55, strokes_expected: 2.68, lie: 'F')
StrokesExpectedShot.create(distance: 60, strokes_expected: 2.70, lie: 'F')
StrokesExpectedShot.create(distance: 65, strokes_expected: 2.72, lie: 'F')
StrokesExpectedShot.create(distance: 70, strokes_expected: 2.73, lie: 'F')
StrokesExpectedShot.create(distance: 75, strokes_expected: 2.74, lie: 'F')
StrokesExpectedShot.create(distance: 80, strokes_expected: 2.75, lie: 'F')
StrokesExpectedShot.create(distance: 85, strokes_expected: 2.76, lie: 'F')
StrokesExpectedShot.create(distance: 90, strokes_expected: 2.78, lie: 'F')
StrokesExpectedShot.create(distance: 95, strokes_expected: 2.79, lie: 'F')

StrokesExpectedShot.create(distance: 100, strokes_expected: 2.80, lie: 'F')
# StrokesExpectedShot.create(distance: 105, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 110, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 115, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 120, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 125, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 130, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 135, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 140, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 145, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 150, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 155, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 160, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 165, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 170, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 175, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 180, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 185, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 190, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 195, strokes_expected: , lie: 'F')

# StrokesExpectedShot.create(distance: 200, strokes_expected: 3.12, lie: 'F')
# StrokesExpectedShot.create(distance: 205, strokes_expected: 3.14, lie: 'F')
# StrokesExpectedShot.create(distance: 210, strokes_expected: 3.15, lie: 'F')
# StrokesExpectedShot.create(distance: 215, strokes_expected: 3.16, lie: 'F')
# StrokesExpectedShot.create(distance: 220, strokes_expected: 3.17, lie: 'F')
# StrokesExpectedShot.create(distance: 225, strokes_expected: 3.19, lie: 'F')
# StrokesExpectedShot.create(distance: 230, strokes_expected: 3.21, lie: 'F')
# StrokesExpectedShot.create(distance: 235, strokes_expected: 3.23, lie: 'F')
# StrokesExpectedShot.create(distance: 240, strokes_expected: 3.25, lie: 'F')
# StrokesExpectedShot.create(distance: 245, strokes_expected: 3.30, lie: 'F')
# StrokesExpectedShot.create(distance: 250, strokes_expected: 3.35, lie: 'F')
# StrokesExpectedShot.create(distance: 255, strokes_expected: 3.40, lie: 'F')
# StrokesExpectedShot.create(distance: 260, strokes_expected: 3.45, lie: 'F')
# StrokesExpectedShot.create(distance: 265, strokes_expected: 3.50, lie: 'F')
# StrokesExpectedShot.create(distance: 270, strokes_expected: 3.55, lie: 'F')
# StrokesExpectedShot.create(distance: 275, strokes_expected: 3.60, lie: 'F')
# StrokesExpectedShot.create(distance: 280, strokes_expected: 3.65, lie: 'F')
# StrokesExpectedShot.create(distance: 285, strokes_expected: 3.67, lie: 'F')
# StrokesExpectedShot.create(distance: 290, strokes_expected: 3.68, lie: 'F')
# StrokesExpectedShot.create(distance: 295, strokes_expected: 3.70, lie: 'F')

# StrokesExpectedShot.create(distance: 300, strokes_expected: 3.71, lie: 'F')
# StrokesExpectedShot.create(distance: 305, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 310, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 315, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 320, strokes_expected: 3.79, lie: 'F')
# StrokesExpectedShot.create(distance: 325, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 330, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 335, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 340, strokes_expected: 3.86, lie: 'F')
# StrokesExpectedShot.create(distance: 345, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 350, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 355, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 360, strokes_expected: 3.92, lie: 'F')
# StrokesExpectedShot.create(distance: 365, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 370, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 375, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 380, strokes_expected: 3.96, lie: 'F')
# StrokesExpectedShot.create(distance: 385, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 390, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 395, strokes_expected: , lie: 'F')

# StrokesExpectedShot.create(distance: 400, strokes_expected: 3.99, lie: 'F')
# StrokesExpectedShot.create(distance: 405, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 410, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 415, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 420, strokes_expected: 4.02, lie: 'F')
# StrokesExpectedShot.create(distance: 425, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 430, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 435, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 440, strokes_expected: 4.08, lie: 'F')
# StrokesExpectedShot.create(distance: 445, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 450, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 455, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 460, strokes_expected: 4.17, lie: 'F')
# StrokesExpectedShot.create(distance: 465, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 470, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 475, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 480, strokes_expected: 4.28, lie: 'F')
# StrokesExpectedShot.create(distance: 485, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 490, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 495, strokes_expected: , lie: 'F')

# StrokesExpectedShot.create(distance: 500, strokes_expected: 4.41, lie: 'F')
# StrokesExpectedShot.create(distance: 505, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 510, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 515, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 520, strokes_expected: 4.54, lie: 'F')
# StrokesExpectedShot.create(distance: 525, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 530, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 535, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 540, strokes_expected: 4.65, lie: 'F')
# StrokesExpectedShot.create(distance: 545, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 550, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 555, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 560, strokes_expected: 4.74, lie: 'F')
# StrokesExpectedShot.create(distance: 565, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 570, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 575, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 580, strokes_expected: 4.79, lie: 'F')
# StrokesExpectedShot.create(distance: 585, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 590, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 595, strokes_expected: , lie: 'F')
# StrokesExpectedShot.create(distance: 600, strokes_expected: 4.82, lie: 'F')

#Rough
# StrokesExpectedShot.create(distance: 10, strokes_expected: 2.80, lie: 'R')
# StrokesExpectedShot.create(distance: 15, strokes_expected: 2.94, lie: 'R')
# StrokesExpectedShot.create(distance: 20, strokes_expected: 2.99, lie: 'R')
# StrokesExpectedShot.create(distance: 25, strokes_expected: 2.99, lie: 'R')
# StrokesExpectedShot.create(distance: 30, strokes_expected: 2.98, lie: 'R')
# StrokesExpectedShot.create(distance: 35, strokes_expected: 2.98, lie: 'R')
# StrokesExpectedShot.create(distance: 40, strokes_expected: 2.97, lie: 'R')
# StrokesExpectedShot.create(distance: 45, strokes_expected: 2.98, lie: 'R')
# StrokesExpectedShot.create(distance: 50, strokes_expected: 2.98, lie: 'R')
# StrokesExpectedShot.create(distance: 55, strokes_expected: 2.99, lie: 'R')
# StrokesExpectedShot.create(distance: 60, strokes_expected: 2.99, lie: 'R')
# StrokesExpectedShot.create(distance: 65, strokes_expected: 3.01, lie: 'R')
# StrokesExpectedShot.create(distance: 70, strokes_expected: 3.02, lie: 'R')
# StrokesExpectedShot.create(distance: 75, strokes_expected: 3.04, lie: 'R')
# StrokesExpectedShot.create(distance: 80, strokes_expected: 3.05, lie: 'R')
# StrokesExpectedShot.create(distance: 85, strokes_expected: 3.07, lie: 'R')
# StrokesExpectedShot.create(distance: 90, strokes_expected: 3.09, lie: 'R')
# StrokesExpectedShot.create(distance: 95, strokes_expected: 3.11, lie: 'R')

# StrokesExpectedShot.create(distance: 100, strokes_expected: 3.02, lie: 'R')
# StrokesExpectedShot.create(distance: 105, strokes_expected: 2.94, lie: 'R')
# StrokesExpectedShot.create(distance: 110, strokes_expected: 2.96, lie: 'R')
# StrokesExpectedShot.create(distance: 115, strokes_expected: 2.98, lie: 'R')
# StrokesExpectedShot.create(distance: 120, strokes_expected: 2.99, lie: 'R')
# StrokesExpectedShot.create(distance: 125, strokes_expected: 2.99, lie: 'R')
# StrokesExpectedShot.create(distance: 130, strokes_expected: 2.98, lie: 'R')
# StrokesExpectedShot.create(distance: 135, strokes_expected: 2.98, lie: 'R')
# StrokesExpectedShot.create(distance: 140, strokes_expected: 2.97, lie: 'R')
# StrokesExpectedShot.create(distance: 145, strokes_expected: 2.98, lie: 'R')
# StrokesExpectedShot.create(distance: 150, strokes_expected: 2.98, lie: 'R')
# StrokesExpectedShot.create(distance: 155, strokes_expected: 2.99, lie: 'R')
# StrokesExpectedShot.create(distance: 160, strokes_expected: 2.99, lie: 'R')
# StrokesExpectedShot.create(distance: 165, strokes_expected: 3.01, lie: 'R')
# StrokesExpectedShot.create(distance: 170, strokes_expected: 3.02, lie: 'R')
# StrokesExpectedShot.create(distance: 175, strokes_expected: 3.04, lie: 'R')
# StrokesExpectedShot.create(distance: 180, strokes_expected: 3.05, lie: 'R')
# StrokesExpectedShot.create(distance: 185, strokes_expected: 3.07, lie: 'R')
# StrokesExpectedShot.create(distance: 190, strokes_expected: 3.09, lie: 'R')
# StrokesExpectedShot.create(distance: 195, strokes_expected: 3.11, lie: 'R')

# StrokesExpectedShot.create(distance: 200, strokes_expected: 3.12, lie: 'R')
# StrokesExpectedShot.create(distance: 205, strokes_expected: 3.14, lie: 'R')
# StrokesExpectedShot.create(distance: 210, strokes_expected: 3.15, lie: 'R')
# StrokesExpectedShot.create(distance: 215, strokes_expected: 3.16, lie: 'R')
# StrokesExpectedShot.create(distance: 220, strokes_expected: 3.17, lie: 'R')
# StrokesExpectedShot.create(distance: 225, strokes_expected: 3.19, lie: 'R')
# StrokesExpectedShot.create(distance: 230, strokes_expected: 3.21, lie: 'R')
# StrokesExpectedShot.create(distance: 235, strokes_expected: 3.23, lie: 'R')
# StrokesExpectedShot.create(distance: 240, strokes_expected: 3.25, lie: 'R')
# StrokesExpectedShot.create(distance: 245, strokes_expected: 3.30, lie: 'R')
# StrokesExpectedShot.create(distance: 250, strokes_expected: 3.35, lie: 'R')
# StrokesExpectedShot.create(distance: 255, strokes_expected: 3.40, lie: 'R')
# StrokesExpectedShot.create(distance: 260, strokes_expected: 3.45, lie: 'R')
# StrokesExpectedShot.create(distance: 265, strokes_expected: 3.50, lie: 'R')
# StrokesExpectedShot.create(distance: 270, strokes_expected: 3.55, lie: 'R')
# StrokesExpectedShot.create(distance: 275, strokes_expected: 3.60, lie: 'R')
# StrokesExpectedShot.create(distance: 280, strokes_expected: 3.65, lie: 'R')
# StrokesExpectedShot.create(distance: 285, strokes_expected: 3.67, lie: 'R')
# StrokesExpectedShot.create(distance: 290, strokes_expected: 3.68, lie: 'R')
# StrokesExpectedShot.create(distance: 295, strokes_expected: 3.70, lie: 'R')

# StrokesExpectedShot.create(distance: 300, strokes_expected: 3.71, lie: 'R')
# StrokesExpectedShot.create(distance: 305, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 310, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 315, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 320, strokes_expected: 3.79, lie: 'R')
# StrokesExpectedShot.create(distance: 325, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 330, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 335, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 340, strokes_expected: 3.86, lie: 'R')
# StrokesExpectedShot.create(distance: 345, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 350, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 355, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 360, strokes_expected: 3.92, lie: 'R')
# StrokesExpectedShot.create(distance: 365, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 370, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 375, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 380, strokes_expected: 3.96, lie: 'R')
# StrokesExpectedShot.create(distance: 385, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 390, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 395, strokes_expected: , lie: 'R')

# StrokesExpectedShot.create(distance: 400, strokes_expected: 3.99, lie: 'R')
# StrokesExpectedShot.create(distance: 405, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 410, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 415, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 420, strokes_expected: 4.02, lie: 'R')
# StrokesExpectedShot.create(distance: 425, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 430, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 435, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 440, strokes_expected: 4.08, lie: 'R')
# StrokesExpectedShot.create(distance: 445, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 450, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 455, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 460, strokes_expected: 4.17, lie: 'R')
# StrokesExpectedShot.create(distance: 465, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 470, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 475, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 480, strokes_expected: 4.28, lie: 'R')
# StrokesExpectedShot.create(distance: 485, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 490, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 495, strokes_expected: , lie: 'R')

# StrokesExpectedShot.create(distance: 500, strokes_expected: 4.41, lie: 'R')
# StrokesExpectedShot.create(distance: 505, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 510, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 515, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 520, strokes_expected: 4.54, lie: 'R')
# StrokesExpectedShot.create(distance: 525, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 530, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 535, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 540, strokes_expected: 4.65, lie: 'R')
# StrokesExpectedShot.create(distance: 545, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 550, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 555, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 560, strokes_expected: 4.74, lie: 'R')
# StrokesExpectedShot.create(distance: 565, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 570, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 575, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 580, strokes_expected: 4.79, lie: 'R')
# StrokesExpectedShot.create(distance: 585, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 590, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 595, strokes_expected: , lie: 'R')
# StrokesExpectedShot.create(distance: 600, strokes_expected: 4.82, lie: 'R')

#Sand
# StrokesExpectedShot.create(distance: 10, strokes_expected: 2.80, lie: 'S')
# StrokesExpectedShot.create(distance: 15, strokes_expected: 2.94, lie: 'S')
# StrokesExpectedShot.create(distance: 20, strokes_expected: 2.99, lie: 'S')
# StrokesExpectedShot.create(distance: 25, strokes_expected: 2.99, lie: 'S')
# StrokesExpectedShot.create(distance: 30, strokes_expected: 2.98, lie: 'S')
# StrokesExpectedShot.create(distance: 35, strokes_expected: 2.98, lie: 'S')
# StrokesExpectedShot.create(distance: 40, strokes_expected: 2.97, lie: 'S')
# StrokesExpectedShot.create(distance: 45, strokes_expected: 2.98, lie: 'S')
# StrokesExpectedShot.create(distance: 50, strokes_expected: 2.98, lie: 'S')
# StrokesExpectedShot.create(distance: 55, strokes_expected: 2.99, lie: 'S')
# StrokesExpectedShot.create(distance: 60, strokes_expected: 2.99, lie: 'S')
# StrokesExpectedShot.create(distance: 65, strokes_expected: 3.01, lie: 'S')
# StrokesExpectedShot.create(distance: 70, strokes_expected: 3.02, lie: 'S')
# StrokesExpectedShot.create(distance: 75, strokes_expected: 3.04, lie: 'S')
# StrokesExpectedShot.create(distance: 80, strokes_expected: 3.05, lie: 'S')
# StrokesExpectedShot.create(distance: 85, strokes_expected: 3.07, lie: 'S')
# StrokesExpectedShot.create(distance: 90, strokes_expected: 3.09, lie: 'S')
# StrokesExpectedShot.create(distance: 95, strokes_expected: 3.11, lie: 'S')

# StrokesExpectedShot.create(distance: 100, strokes_expected: 3.23, lie: 'S')
# StrokesExpectedShot.create(distance: 105, strokes_expected: 2.94, lie: 'S')
# StrokesExpectedShot.create(distance: 110, strokes_expected: 2.96, lie: 'S')
# StrokesExpectedShot.create(distance: 115, strokes_expected: 2.98, lie: 'S')
# StrokesExpectedShot.create(distance: 120, strokes_expected: 2.99, lie: 'S')
# StrokesExpectedShot.create(distance: 125, strokes_expected: 2.99, lie: 'S')
# StrokesExpectedShot.create(distance: 130, strokes_expected: 2.98, lie: 'S')
# StrokesExpectedShot.create(distance: 135, strokes_expected: 2.98, lie: 'S')
# StrokesExpectedShot.create(distance: 140, strokes_expected: 2.97, lie: 'S')
# StrokesExpectedShot.create(distance: 145, strokes_expected: 2.98, lie: 'S')
# StrokesExpectedShot.create(distance: 150, strokes_expected: 2.98, lie: 'S')
# StrokesExpectedShot.create(distance: 155, strokes_expected: 2.99, lie: 'S')
# StrokesExpectedShot.create(distance: 160, strokes_expected: 2.99, lie: 'S')
# StrokesExpectedShot.create(distance: 165, strokes_expected: 3.01, lie: 'S')
# StrokesExpectedShot.create(distance: 170, strokes_expected: 3.02, lie: 'S')
# StrokesExpectedShot.create(distance: 175, strokes_expected: 3.04, lie: 'S')
# StrokesExpectedShot.create(distance: 180, strokes_expected: 3.05, lie: 'S')
# StrokesExpectedShot.create(distance: 185, strokes_expected: 3.07, lie: 'S')
# StrokesExpectedShot.create(distance: 190, strokes_expected: 3.09, lie: 'S')
# StrokesExpectedShot.create(distance: 195, strokes_expected: 3.11, lie: 'S')

# StrokesExpectedShot.create(distance: 200, strokes_expected: 3.12, lie: 'S')
# StrokesExpectedShot.create(distance: 205, strokes_expected: 3.14, lie: 'S')
# StrokesExpectedShot.create(distance: 210, strokes_expected: 3.15, lie: 'S')
# StrokesExpectedShot.create(distance: 215, strokes_expected: 3.16, lie: 'S')
# StrokesExpectedShot.create(distance: 220, strokes_expected: 3.17, lie: 'S')
# StrokesExpectedShot.create(distance: 225, strokes_expected: 3.19, lie: 'S')
# StrokesExpectedShot.create(distance: 230, strokes_expected: 3.21, lie: 'S')
# StrokesExpectedShot.create(distance: 235, strokes_expected: 3.23, lie: 'S')
# StrokesExpectedShot.create(distance: 240, strokes_expected: 3.25, lie: 'S')
# StrokesExpectedShot.create(distance: 245, strokes_expected: 3.30, lie: 'S')
# StrokesExpectedShot.create(distance: 250, strokes_expected: 3.35, lie: 'S')
# StrokesExpectedShot.create(distance: 255, strokes_expected: 3.40, lie: 'S')
# StrokesExpectedShot.create(distance: 260, strokes_expected: 3.45, lie: 'S')
# StrokesExpectedShot.create(distance: 265, strokes_expected: 3.50, lie: 'S')
# StrokesExpectedShot.create(distance: 270, strokes_expected: 3.55, lie: 'S')
# StrokesExpectedShot.create(distance: 275, strokes_expected: 3.60, lie: 'S')
# StrokesExpectedShot.create(distance: 280, strokes_expected: 3.65, lie: 'S')
# StrokesExpectedShot.create(distance: 285, strokes_expected: 3.67, lie: 'S')
# StrokesExpectedShot.create(distance: 290, strokes_expected: 3.68, lie: 'S')
# StrokesExpectedShot.create(distance: 295, strokes_expected: 3.70, lie: 'S')

# StrokesExpectedShot.create(distance: 300, strokes_expected: 3.71, lie: 'S')
# StrokesExpectedShot.create(distance: 305, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 310, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 315, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 320, strokes_expected: 3.79, lie: 'S')
# StrokesExpectedShot.create(distance: 325, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 330, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 335, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 340, strokes_expected: 3.86, lie: 'S')
# StrokesExpectedShot.create(distance: 345, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 350, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 355, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 360, strokes_expected: 3.92, lie: 'S')
# StrokesExpectedShot.create(distance: 365, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 370, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 375, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 380, strokes_expected: 3.96, lie: 'S')
# StrokesExpectedShot.create(distance: 385, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 390, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 395, strokes_expected: , lie: 'S')

# StrokesExpectedShot.create(distance: 400, strokes_expected: 3.99, lie: 'S')
# StrokesExpectedShot.create(distance: 405, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 410, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 415, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 420, strokes_expected: 4.02, lie: 'S')
# StrokesExpectedShot.create(distance: 425, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 430, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 435, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 440, strokes_expected: 4.08, lie: 'S')
# StrokesExpectedShot.create(distance: 445, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 450, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 455, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 460, strokes_expected: 4.17, lie: 'S')
# StrokesExpectedShot.create(distance: 465, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 470, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 475, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 480, strokes_expected: 4.28, lie: 'S')
# StrokesExpectedShot.create(distance: 485, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 490, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 495, strokes_expected: , lie: 'S')

# StrokesExpectedShot.create(distance: 500, strokes_expected: 4.41, lie: 'S')
# StrokesExpectedShot.create(distance: 505, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 510, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 515, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 520, strokes_expected: 4.54, lie: 'S')
# StrokesExpectedShot.create(distance: 525, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 530, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 535, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 540, strokes_expected: 4.65, lie: 'S')
# StrokesExpectedShot.create(distance: 545, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 550, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 555, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 560, strokes_expected: 4.74, lie: 'S')
# StrokesExpectedShot.create(distance: 565, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 570, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 575, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 580, strokes_expected: 4.79, lie: 'S')
# StrokesExpectedShot.create(distance: 585, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 590, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 595, strokes_expected: , lie: 'S')
# StrokesExpectedShot.create(distance: 600, strokes_expected: 4.82, lie: 'S')

#Recovery
# StrokesExpectedShot.create(distance: 10, strokes_expected: 2.80, lie: 'X')
# StrokesExpectedShot.create(distance: 15, strokes_expected: 2.94, lie: 'X')
# StrokesExpectedShot.create(distance: 20, strokes_expected: 2.99, lie: 'X')
# StrokesExpectedShot.create(distance: 25, strokes_expected: 2.99, lie: 'X')
# StrokesExpectedShot.create(distance: 30, strokes_expected: 2.98, lie: 'X')
# StrokesExpectedShot.create(distance: 35, strokes_expected: 2.98, lie: 'X')
# StrokesExpectedShot.create(distance: 40, strokes_expected: 2.97, lie: 'X')
# StrokesExpectedShot.create(distance: 45, strokes_expected: 2.98, lie: 'X')
# StrokesExpectedShot.create(distance: 50, strokes_expected: 2.98, lie: 'X')
# StrokesExpectedShot.create(distance: 55, strokes_expected: 2.99, lie: 'X')
# StrokesExpectedShot.create(distance: 60, strokes_expected: 2.99, lie: 'X')
# StrokesExpectedShot.create(distance: 65, strokes_expected: 3.01, lie: 'X')
# StrokesExpectedShot.create(distance: 70, strokes_expected: 3.02, lie: 'X')
# StrokesExpectedShot.create(distance: 75, strokes_expected: 3.04, lie: 'X')
# StrokesExpectedShot.create(distance: 80, strokes_expected: 3.05, lie: 'X')
# StrokesExpectedShot.create(distance: 85, strokes_expected: 3.07, lie: 'X')
# StrokesExpectedShot.create(distance: 90, strokes_expected: 3.09, lie: 'X')
# StrokesExpectedShot.create(distance: 95, strokes_expected: 3.11, lie: 'X')

# StrokesExpectedShot.create(distance: 100, strokes_expected: 3.80, lie: 'X')
# StrokesExpectedShot.create(distance: 105, strokes_expected: 2.94, lie: 'X')
# StrokesExpectedShot.create(distance: 110, strokes_expected: 2.96, lie: 'X')
# StrokesExpectedShot.create(distance: 115, strokes_expected: 2.98, lie: 'X')
# StrokesExpectedShot.create(distance: 120, strokes_expected: 2.99, lie: 'X')
# StrokesExpectedShot.create(distance: 125, strokes_expected: 2.99, lie: 'X')
# StrokesExpectedShot.create(distance: 130, strokes_expected: 2.98, lie: 'X')
# StrokesExpectedShot.create(distance: 135, strokes_expected: 2.98, lie: 'X')
# StrokesExpectedShot.create(distance: 140, strokes_expected: 2.97, lie: 'X')
# StrokesExpectedShot.create(distance: 145, strokes_expected: 2.98, lie: 'X')
# StrokesExpectedShot.create(distance: 150, strokes_expected: 2.98, lie: 'X')
# StrokesExpectedShot.create(distance: 155, strokes_expected: 2.99, lie: 'X')
# StrokesExpectedShot.create(distance: 160, strokes_expected: 2.99, lie: 'X')
# StrokesExpectedShot.create(distance: 165, strokes_expected: 3.01, lie: 'X')
# StrokesExpectedShot.create(distance: 170, strokes_expected: 3.02, lie: 'X')
# StrokesExpectedShot.create(distance: 175, strokes_expected: 3.04, lie: 'X')
# StrokesExpectedShot.create(distance: 180, strokes_expected: 3.05, lie: 'X')
# StrokesExpectedShot.create(distance: 185, strokes_expected: 3.07, lie: 'X')
# StrokesExpectedShot.create(distance: 190, strokes_expected: 3.09, lie: 'X')
# StrokesExpectedShot.create(distance: 195, strokes_expected: 3.11, lie: 'X')

# StrokesExpectedShot.create(distance: 200, strokes_expected: 3.12, lie: 'X')
# StrokesExpectedShot.create(distance: 205, strokes_expected: 3.14, lie: 'X')
# StrokesExpectedShot.create(distance: 210, strokes_expected: 3.15, lie: 'X')
# StrokesExpectedShot.create(distance: 215, strokes_expected: 3.16, lie: 'X')
# StrokesExpectedShot.create(distance: 220, strokes_expected: 3.17, lie: 'X')
# StrokesExpectedShot.create(distance: 225, strokes_expected: 3.19, lie: 'X')
# StrokesExpectedShot.create(distance: 230, strokes_expected: 3.21, lie: 'X')
# StrokesExpectedShot.create(distance: 235, strokes_expected: 3.23, lie: 'X')
# StrokesExpectedShot.create(distance: 240, strokes_expected: 3.25, lie: 'X')
# StrokesExpectedShot.create(distance: 245, strokes_expected: 3.30, lie: 'X')
# StrokesExpectedShot.create(distance: 250, strokes_expected: 3.35, lie: 'X')
# StrokesExpectedShot.create(distance: 255, strokes_expected: 3.40, lie: 'X')
# StrokesExpectedShot.create(distance: 260, strokes_expected: 3.45, lie: 'X')
# StrokesExpectedShot.create(distance: 265, strokes_expected: 3.50, lie: 'X')
# StrokesExpectedShot.create(distance: 270, strokes_expected: 3.55, lie: 'X')
# StrokesExpectedShot.create(distance: 275, strokes_expected: 3.60, lie: 'X')
# StrokesExpectedShot.create(distance: 280, strokes_expected: 3.65, lie: 'X')
# StrokesExpectedShot.create(distance: 285, strokes_expected: 3.67, lie: 'X')
# StrokesExpectedShot.create(distance: 290, strokes_expected: 3.68, lie: 'X')
# StrokesExpectedShot.create(distance: 295, strokes_expected: 3.70, lie: 'X')

# StrokesExpectedShot.create(distance: 300, strokes_expected: 3.71, lie: 'X')
# StrokesExpectedShot.create(distance: 305, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 310, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 315, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 320, strokes_expected: 3.79, lie: 'X')
# StrokesExpectedShot.create(distance: 325, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 330, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 335, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 340, strokes_expected: 3.86, lie: 'X')
# StrokesExpectedShot.create(distance: 345, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 350, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 355, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 360, strokes_expected: 3.92, lie: 'X')
# StrokesExpectedShot.create(distance: 365, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 370, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 375, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 380, strokes_expected: 3.96, lie: 'X')
# StrokesExpectedShot.create(distance: 385, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 390, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 395, strokes_expected: , lie: 'X')

# StrokesExpectedShot.create(distance: 400, strokes_expected: 3.99, lie: 'X')
# StrokesExpectedShot.create(distance: 405, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 410, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 415, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 420, strokes_expected: 4.02, lie: 'X')
# StrokesExpectedShot.create(distance: 425, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 430, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 435, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 440, strokes_expected: 4.08, lie: 'X')
# StrokesExpectedShot.create(distance: 445, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 450, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 455, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 460, strokes_expected: 4.17, lie: 'X')
# StrokesExpectedShot.create(distance: 465, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 470, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 475, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 480, strokes_expected: 4.28, lie: 'X')
# StrokesExpectedShot.create(distance: 485, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 490, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 495, strokes_expected: , lie: 'X')

# StrokesExpectedShot.create(distance: 500, strokes_expected: 4.41, lie: 'X')
# StrokesExpectedShot.create(distance: 505, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 510, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 515, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 520, strokes_expected: 4.54, lie: 'X')
# StrokesExpectedShot.create(distance: 525, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 530, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 535, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 540, strokes_expected: 4.65, lie: 'X')
# StrokesExpectedShot.create(distance: 545, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 550, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 555, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 560, strokes_expected: 4.74, lie: 'X')
# StrokesExpectedShot.create(distance: 565, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 570, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 575, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 580, strokes_expected: 4.79, lie: 'X')
# StrokesExpectedShot.create(distance: 585, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 590, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 595, strokes_expected: , lie: 'X')
# StrokesExpectedShot.create(distance: 600, strokes_expected: 4.82, lie: 'X')

