require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StrokesExpectedShotsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # StrokesExpectedShot. As you add validations to StrokesExpectedShot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StrokesExpectedShotsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all strokes_expected_shots as @strokes_expected_shots" do
      strokes_expected_shot = StrokesExpectedShot.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:strokes_expected_shots)).to eq([strokes_expected_shot])
    end
  end

  describe "GET #show" do
    it "assigns the requested strokes_expected_shot as @strokes_expected_shot" do
      strokes_expected_shot = StrokesExpectedShot.create! valid_attributes
      get :show, {:id => strokes_expected_shot.to_param}, valid_session
      expect(assigns(:strokes_expected_shot)).to eq(strokes_expected_shot)
    end
  end

  describe "GET #new" do
    it "assigns a new strokes_expected_shot as @strokes_expected_shot" do
      get :new, {}, valid_session
      expect(assigns(:strokes_expected_shot)).to be_a_new(StrokesExpectedShot)
    end
  end

  describe "GET #edit" do
    it "assigns the requested strokes_expected_shot as @strokes_expected_shot" do
      strokes_expected_shot = StrokesExpectedShot.create! valid_attributes
      get :edit, {:id => strokes_expected_shot.to_param}, valid_session
      expect(assigns(:strokes_expected_shot)).to eq(strokes_expected_shot)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new StrokesExpectedShot" do
        expect {
          post :create, {:strokes_expected_shot => valid_attributes}, valid_session
        }.to change(StrokesExpectedShot, :count).by(1)
      end

      it "assigns a newly created strokes_expected_shot as @strokes_expected_shot" do
        post :create, {:strokes_expected_shot => valid_attributes}, valid_session
        expect(assigns(:strokes_expected_shot)).to be_a(StrokesExpectedShot)
        expect(assigns(:strokes_expected_shot)).to be_persisted
      end

      it "redirects to the created strokes_expected_shot" do
        post :create, {:strokes_expected_shot => valid_attributes}, valid_session
        expect(response).to redirect_to(StrokesExpectedShot.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved strokes_expected_shot as @strokes_expected_shot" do
        post :create, {:strokes_expected_shot => invalid_attributes}, valid_session
        expect(assigns(:strokes_expected_shot)).to be_a_new(StrokesExpectedShot)
      end

      it "re-renders the 'new' template" do
        post :create, {:strokes_expected_shot => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested strokes_expected_shot" do
        strokes_expected_shot = StrokesExpectedShot.create! valid_attributes
        put :update, {:id => strokes_expected_shot.to_param, :strokes_expected_shot => new_attributes}, valid_session
        strokes_expected_shot.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested strokes_expected_shot as @strokes_expected_shot" do
        strokes_expected_shot = StrokesExpectedShot.create! valid_attributes
        put :update, {:id => strokes_expected_shot.to_param, :strokes_expected_shot => valid_attributes}, valid_session
        expect(assigns(:strokes_expected_shot)).to eq(strokes_expected_shot)
      end

      it "redirects to the strokes_expected_shot" do
        strokes_expected_shot = StrokesExpectedShot.create! valid_attributes
        put :update, {:id => strokes_expected_shot.to_param, :strokes_expected_shot => valid_attributes}, valid_session
        expect(response).to redirect_to(strokes_expected_shot)
      end
    end

    context "with invalid params" do
      it "assigns the strokes_expected_shot as @strokes_expected_shot" do
        strokes_expected_shot = StrokesExpectedShot.create! valid_attributes
        put :update, {:id => strokes_expected_shot.to_param, :strokes_expected_shot => invalid_attributes}, valid_session
        expect(assigns(:strokes_expected_shot)).to eq(strokes_expected_shot)
      end

      it "re-renders the 'edit' template" do
        strokes_expected_shot = StrokesExpectedShot.create! valid_attributes
        put :update, {:id => strokes_expected_shot.to_param, :strokes_expected_shot => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested strokes_expected_shot" do
      strokes_expected_shot = StrokesExpectedShot.create! valid_attributes
      expect {
        delete :destroy, {:id => strokes_expected_shot.to_param}, valid_session
      }.to change(StrokesExpectedShot, :count).by(-1)
    end

    it "redirects to the strokes_expected_shots list" do
      strokes_expected_shot = StrokesExpectedShot.create! valid_attributes
      delete :destroy, {:id => strokes_expected_shot.to_param}, valid_session
      expect(response).to redirect_to(strokes_expected_shots_url)
    end
  end

end
